//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Movil.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SportsGoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SportsGoResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpinn.SportsGo.Movil.Resources.SportsGoResources", typeof(SportsGoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept terms and conditions, see here!..
        /// </summary>
        internal static string AceptaTerminos {
            get {
                return ResourceManager.GetString("AceptaTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @_NombrePersona_@ has added you to his contacts.
        /// </summary>
        internal static string AgregadoPersonaDescripcion {
            get {
                return ResourceManager.GetString("AgregadoPersonaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have added by a new person!.
        /// </summary>
        internal static string AgregadoPersonaTitulo {
            get {
                return ResourceManager.GetString("AgregadoPersonaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Person.
        /// </summary>
        internal static string AgregarContacto {
            get {
                return ResourceManager.GetString("AgregarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  + Add Sport.
        /// </summary>
        internal static string AgregarDeporte {
            get {
                return ResourceManager.GetString("AgregarDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Add Event.
        /// </summary>
        internal static string AgregarEvento {
            get {
                return ResourceManager.GetString("AgregarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Add Video.
        /// </summary>
        internal static string AgregarVideo {
            get {
                return ResourceManager.GetString("AgregarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height (cm).
        /// </summary>
        internal static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attach Receipt.
        /// </summary>
        internal static string AnexarRecibo {
            get {
                return ResourceManager.GetString("AnexarRecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annual.
        /// </summary>
        internal static string Anual {
            get {
                return ResourceManager.GetString("Anual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Filter.
        /// </summary>
        internal static string AplicarFiltro {
            get {
                return ResourceManager.GetString("AplicarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approved.
        /// </summary>
        internal static string Aprobado {
            get {
                return ResourceManager.GetString("Aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attach the receipt of payment to be able to continue with the process!..
        /// </summary>
        internal static string ArchivoNecesarioParaElPago {
            get {
                return ResourceManager.GetString("ArchivoNecesarioParaElPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Will attend.
        /// </summary>
        internal static string Asistiran {
            get {
                return ResourceManager.GetString("Asistiran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Will you attend?.
        /// </summary>
        internal static string Asistiras {
            get {
                return ResourceManager.GetString("Asistiras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication with SportsGo.
        /// </summary>
        internal static string AutenticacionSportsGo {
            get {
                return ResourceManager.GetString("AutenticacionSportsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bimonthly.
        /// </summary>
        internal static string Bimestral {
            get {
                return ResourceManager.GetString("Bimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biography.
        /// </summary>
        internal static string Biografia {
            get {
                return ResourceManager.GetString("Biografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete photo.
        /// </summary>
        internal static string BorrarFoto {
            get {
                return ResourceManager.GetString("BorrarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Here!..
        /// </summary>
        internal static string BuscaAqui {
            get {
                return ResourceManager.GetString("BuscaAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for relevant skills.
        /// </summary>
        internal static string BuscaPorHabilidadesRelevantes {
            get {
                return ResourceManager.GetString("BuscaPorHabilidadesRelevantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for the sports of your interest!..
        /// </summary>
        internal static string BuscaPorLosDeportesDeTuInteres {
            get {
                return ResourceManager.GetString("BuscaPorLosDeportesDeTuInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera no available :(.
        /// </summary>
        internal static string CamaraNoDisponible {
            get {
                return ResourceManager.GetString("CamaraNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change File?.
        /// </summary>
        internal static string CambiarArchivo {
            get {
                return ResourceManager.GetString("CambiarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Plan.
        /// </summary>
        internal static string CambiarPlan {
            get {
                return ResourceManager.GetString("CambiarPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading!..
        /// </summary>
        internal static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign off.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must contain at least 8 characters, 1 capital letter, 1 number and no special characters!.
        /// </summary>
        internal static string ClaveFormatoInvalido {
            get {
                return ResourceManager.GetString("ClaveFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy Plan.
        /// </summary>
        internal static string ComprarPlan {
            get {
                return ResourceManager.GetString("ComprarPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It looks like you&apos;re not connected to the internet!..
        /// </summary>
        internal static string ConexionPerdida {
            get {
                return ResourceManager.GetString("ConexionPerdida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account settings.
        /// </summary>
        internal static string ConfiguracionDeLaCuenta {
            get {
                return ResourceManager.GetString("ConfiguracionDeLaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string ConfirmaContraseña {
            get {
                return ResourceManager.GetString("ConfirmaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Athletes search.
        /// </summary>
        internal static string ConsultaDeportistas {
            get {
                return ResourceManager.GetString("ConsultaDeportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events search.
        /// </summary>
        internal static string ConsultaEventos {
            get {
                return ResourceManager.GetString("ConsultaEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group search.
        /// </summary>
        internal static string ConsultaGrupos {
            get {
                return ResourceManager.GetString("ConsultaGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacts.
        /// </summary>
        internal static string Contactos {
            get {
                return ResourceManager.GetString("Contactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords are different!..
        /// </summary>
        internal static string ContraseñasDiferentes {
            get {
                return ResourceManager.GetString("ContraseñasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create an Account.
        /// </summary>
        internal static string CrearCuenta {
            get {
                return ResourceManager.GetString("CrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Sport.
        /// </summary>
        internal static string CrearDeporte {
            get {
                return ResourceManager.GetString("CrearDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Events.
        /// </summary>
        internal static string CrearEventos {
            get {
                return ResourceManager.GetString("CrearEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Profile.
        /// </summary>
        internal static string CrearPerfil {
            get {
                return ResourceManager.GetString("CrearPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Post.
        /// </summary>
        internal static string CrearPublicacion {
            get {
                return ResourceManager.GetString("CrearPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        internal static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account you are trying to log in with is not active.
        /// </summary>
        internal static string CuentaNoActiva {
            get {
                return ResourceManager.GetString("CuentaNoActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account data.
        /// </summary>
        internal static string DatosDeLaCuenta {
            get {
                return ResourceManager.GetString("DatosDeLaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must accept the terms and conditions of use !..
        /// </summary>
        internal static string DebesAceptarTerminos {
            get {
                return ResourceManager.GetString("DebesAceptarTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must register at least one skill!..
        /// </summary>
        internal static string DebesRegistrarHabilidad {
            get {
                return ResourceManager.GetString("DebesRegistrarHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a sport!..
        /// </summary>
        internal static string DebesSeleccionarDeporte {
            get {
                return ResourceManager.GetString("DebesSeleccionarDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too Many Attempts!.
        /// </summary>
        internal static string DemasiadosIntentos {
            get {
                return ResourceManager.GetString("DemasiadosIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sports.
        /// </summary>
        internal static string Deportes {
            get {
                return ResourceManager.GetString("Deportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Athletes.
        /// </summary>
        internal static string Deportistas {
            get {
                return ResourceManager.GetString("Deportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @_NombrePersona_@  is no longer going to attend @_TituloEvento_@!..
        /// </summary>
        internal static string DesuscripcionEventoDescripcion {
            get {
                return ResourceManager.GetString("DesuscripcionEventoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Someone is no longer going to attend one of your events!..
        /// </summary>
        internal static string DesuscripcionEventoTitulo {
            get {
                return ResourceManager.GetString("DesuscripcionEventoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify your data or link / unlink services.
        /// </summary>
        internal static string DetalleDatosDeLaCuenta {
            get {
                return ResourceManager.GetString("DetalleDatosDeLaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Athletes detail.
        /// </summary>
        internal static string DetalleDeportistas {
            get {
                return ResourceManager.GetString("DetalleDeportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group detail.
        /// </summary>
        internal static string DetalleGrupos {
            get {
                return ResourceManager.GetString("DetalleGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail on all your payments.
        /// </summary>
        internal static string DetalleHistorialPagos {
            get {
                return ResourceManager.GetString("DetalleHistorialPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify or view your account plan.
        /// </summary>
        internal static string DetallePlanDeLaCuenta {
            get {
                return ResourceManager.GetString("DetallePlanDeLaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the application theme.
        /// </summary>
        internal static string DetalleTemasDeLaAplicacion {
            get {
                return ResourceManager.GetString("DetalleTemasDeLaAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open our terms and conditions.
        /// </summary>
        internal static string DetalleTerminosYCondiciones {
            get {
                return ResourceManager.GetString("DetalleTerminosYCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age.
        /// </summary>
        internal static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Sport.
        /// </summary>
        internal static string EditarDeporte {
            get {
                return ResourceManager.GetString("EditarDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Edit Information.
        /// </summary>
        internal static string EditarInformacionPersonal {
            get {
                return ResourceManager.GetString("EditarInformacionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        internal static string EditarPerfil {
            get {
                return ResourceManager.GetString("EditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Post.
        /// </summary>
        internal static string EditarPublicacion {
            get {
                return ResourceManager.GetString("EditarPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick photo.
        /// </summary>
        internal static string ElegirFoto {
            get {
                return ResourceManager.GetString("ElegirFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick video.
        /// </summary>
        internal static string ElegirVideo {
            get {
                return ResourceManager.GetString("ElegirVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your sport of interest!..
        /// </summary>
        internal static string EligeTuDeporteInteres {
            get {
                return ResourceManager.GetString("EligeTuDeporteInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @_NombrePersona_@ te ha eliminado de sus contactos.
        /// </summary>
        internal static string EliminadoPersonaDescripcion {
            get {
                return ResourceManager.GetString("EliminadoPersonaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been deleted by one of your contacts!..
        /// </summary>
        internal static string EliminadoPersonaTitulo {
            get {
                return ResourceManager.GetString("EliminadoPersonaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Person.
        /// </summary>
        internal static string EliminarContacto {
            get {
                return ResourceManager.GetString("EliminarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email of the user has an invalid format!..
        /// </summary>
        internal static string EmailFormatoInvalido {
            get {
                return ResourceManager.GetString("EmailFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email of the person in charge has an invalid format!..
        /// </summary>
        internal static string EmailFormatoInvalidoResponsable {
            get {
                return ResourceManager.GetString("EmailFormatoInvalidoResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email already exists!..
        /// </summary>
        internal static string EmailYaExiste {
            get {
                return ResourceManager.GetString("EmailYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Here!..
        /// </summary>
        internal static string EntraAqui {
            get {
                return ResourceManager.GetString("EntraAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to consult payment information!..
        /// </summary>
        internal static string ErrorAlConsultarInfoPagos {
            get {
                return ResourceManager.GetString("ErrorAlConsultarInfoPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error processing your file!..
        /// </summary>
        internal static string ErrorArchivo {
            get {
                return ResourceManager.GetString("ErrorArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error saving your images !..
        /// </summary>
        internal static string ErrorAsignarImagenes {
            get {
                return ResourceManager.GetString("ErrorAsignarImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting chat!..
        /// </summary>
        internal static string ErrorBorrarChat {
            get {
                return ResourceManager.GetString("ErrorBorrarChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not check your payment history!..
        /// </summary>
        internal static string ErrorConsultarHistorialPagos {
            get {
                return ResourceManager.GetString("ErrorConsultarHistorialPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to remove the sport!..
        /// </summary>
        internal static string ErrorEliminarDeporte {
            get {
                return ResourceManager.GetString("ErrorEliminarDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to remove the skill!..
        /// </summary>
        internal static string ErrorEliminarHabilidad {
            get {
                return ResourceManager.GetString("ErrorEliminarHabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error deleting your images !..
        /// </summary>
        internal static string ErrorEliminarImagenes {
            get {
                return ResourceManager.GetString("ErrorEliminarImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save the sport!..
        /// </summary>
        internal static string ErrorGuardarDeporte {
            get {
                return ResourceManager.GetString("ErrorGuardarDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save skills!..
        /// </summary>
        internal static string ErrorGuardarHabilidades {
            get {
                return ResourceManager.GetString("ErrorGuardarHabilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error saving your information!..
        /// </summary>
        internal static string ErrorGuardarInformacionPersonal {
            get {
                return ResourceManager.GetString("ErrorGuardarInformacionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something happened, could not login!..
        /// </summary>
        internal static string ErrorIniciarSesion {
            get {
                return ResourceManager.GetString("ErrorIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to query sports!..
        /// </summary>
        internal static string ErrorListarDeportes {
            get {
                return ResourceManager.GetString("ErrorListarDeportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to query skills!..
        /// </summary>
        internal static string ErrorListarHabilidades {
            get {
                return ResourceManager.GetString("ErrorListarHabilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to modify account!..
        /// </summary>
        internal static string ErrorModificarCuenta {
            get {
                return ResourceManager.GetString("ErrorModificarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error modifying account!..
        /// </summary>
        internal static string ErrorModificarUsuario {
            get {
                return ResourceManager.GetString("ErrorModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been created but it was not possible to make the first login :( Reopen the application and try to login with your new user !..
        /// </summary>
        internal static string ErrorPrimerLogeo {
            get {
                return ResourceManager.GetString("ErrorPrimerLogeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error saving your registration!..
        /// </summary>
        internal static string ErrorPrimerRegistro {
            get {
                return ResourceManager.GetString("ErrorPrimerRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error processing your post!..
        /// </summary>
        internal static string ErrorPublicacion {
            get {
                return ResourceManager.GetString("ErrorPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovering password failed!..
        /// </summary>
        internal static string ErrorRecuperarClave {
            get {
                return ResourceManager.GetString("ErrorRecuperarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error validating email!..
        /// </summary>
        internal static string ErrorValidarEmail {
            get {
                return ResourceManager.GetString("ErrorValidarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error validating user!..
        /// </summary>
        internal static string ErrorValidarUsuario {
            get {
                return ResourceManager.GetString("ErrorValidarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the lastname here!..
        /// </summary>
        internal static string EscribeApellidoResponsable {
            get {
                return ResourceManager.GetString("EscribeApellidoResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the payment code here!.
        /// </summary>
        internal static string EscribeCodigoPagoAqui {
            get {
                return ResourceManager.GetString("EscribeCodigoPagoAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the email here!.
        /// </summary>
        internal static string EscribeEmailResponsable {
            get {
                return ResourceManager.GetString("EscribeEmailResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your email, username and the option with which you want to recover!..
        /// </summary>
        internal static string EscribeEmailUsuario {
            get {
                return ResourceManager.GetString("EscribeEmailUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the name here!..
        /// </summary>
        internal static string EscribeNombreResponsable {
            get {
                return ResourceManager.GetString("EscribeNombreResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the skype here!.
        /// </summary>
        internal static string EscribeSkypeResponsable {
            get {
                return ResourceManager.GetString("EscribeSkypeResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the landline phone here!.
        /// </summary>
        internal static string EscribeTelefonoFijo {
            get {
                return ResourceManager.GetString("EscribeTelefonoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the mobile phone here!.
        /// </summary>
        internal static string EscribeTelefonoMovil {
            get {
                return ResourceManager.GetString("EscribeTelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your alias here!..
        /// </summary>
        internal static string EscribeTuAlias {
            get {
                return ResourceManager.GetString("EscribeTuAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your lastname here!..
        /// </summary>
        internal static string EscribeTuApellido {
            get {
                return ResourceManager.GetString("EscribeTuApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your city here!..
        /// </summary>
        internal static string EscribeTuCiudad {
            get {
                return ResourceManager.GetString("EscribeTuCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password here!.
        /// </summary>
        internal static string EscribeTuClave {
            get {
                return ResourceManager.GetString("EscribeTuClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email here!..
        /// </summary>
        internal static string EscribeTuEmail {
            get {
                return ResourceManager.GetString("EscribeTuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your name here!..
        /// </summary>
        internal static string EscribeTuNombre {
            get {
                return ResourceManager.GetString("EscribeTuNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your contact name here!.
        /// </summary>
        internal static string EscribeTuNombreContacto {
            get {
                return ResourceManager.GetString("EscribeTuNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your ID here!..
        /// </summary>
        internal static string EscribeTuNumeroIdentificacion {
            get {
                return ResourceManager.GetString("EscribeTuNumeroIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your Skype here.
        /// </summary>
        internal static string EscribeTuSkype {
            get {
                return ResourceManager.GetString("EscribeTuSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your payment remarks here.
        /// </summary>
        internal static string EscribeTusObservaciones {
            get {
                return ResourceManager.GetString("EscribeTusObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your phone here!.
        /// </summary>
        internal static string EscribeTuTelefono {
            get {
                return ResourceManager.GetString("EscribeTuTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your username here!.
        /// </summary>
        internal static string EscribeTuUsuario {
            get {
                return ResourceManager.GetString("EscribeTuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hold Pay.
        /// </summary>
        internal static string EsperaPago {
            get {
                return ResourceManager.GetString("EsperaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spent Stars.
        /// </summary>
        internal static string EstrellasGastadas {
            get {
                return ResourceManager.GetString("EstrellasGastadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string Eventos {
            get {
                return ResourceManager.GetString("Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must register at least one sport !..
        /// </summary>
        internal static string FaltaDatosDeporte {
            get {
                return ResourceManager.GetString("FaltaDatosDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data to fill out your profile information!..
        /// </summary>
        internal static string FaltaDatosPerfil {
            get {
                return ResourceManager.GetString("FaltaDatosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data to fill out your personal information!..
        /// </summary>
        internal static string FaltaDatosPersona {
            get {
                return ResourceManager.GetString("FaltaDatosPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data to fill out your post!..
        /// </summary>
        internal static string FaltaDatosPublicacion {
            get {
                return ResourceManager.GetString("FaltaDatosPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account details are missing!.
        /// </summary>
        internal static string FaltanDatosCuenta {
            get {
                return ResourceManager.GetString("FaltanDatosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are missing data to fill the responsible of the athlete!..
        /// </summary>
        internal static string FaltanDatosResponsable {
            get {
                return ResourceManager.GetString("FaltanDatosResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing a video to fill out your post!..
        /// </summary>
        internal static string FaltaVideoPublicacion {
            get {
                return ResourceManager.GetString("FaltaVideoPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of State:.
        /// </summary>
        internal static string FechaEstado {
            get {
                return ResourceManager.GetString("FechaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final date.
        /// </summary>
        internal static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        internal static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth date.
        /// </summary>
        internal static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The end date of the event can not be less than the start date.
        /// </summary>
        internal static string FechasEventoInvalida {
            get {
                return ResourceManager.GetString("FechasEventoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        internal static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Physical.
        /// </summary>
        internal static string Fisicas {
            get {
                return ResourceManager.GetString("Fisicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo.
        /// </summary>
        internal static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gallery no available :(.
        /// </summary>
        internal static string GaleriaNoDisponible {
            get {
                return ResourceManager.GetString("GaleriaNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups.
        /// </summary>
        internal static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skills.
        /// </summary>
        internal static string Habilidades {
            get {
                return ResourceManager.GetString("Habilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current skills.
        /// </summary>
        internal static string HabilidadesActuales {
            get {
                return ResourceManager.GetString("HabilidadesActuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Skills.
        /// </summary>
        internal static string HabilidadesSeleccionadas {
            get {
                return ResourceManager.GetString("HabilidadesSeleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check the plans available by the name &quot;@_NombrePlan_@&quot; and look at their new options and prices.
        /// </summary>
        internal static string HayUnNuevoPlanDescripcion {
            get {
                return ResourceManager.GetString("HayUnNuevoPlanDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a new plan for your account type!..
        /// </summary>
        internal static string HayUnNuevoPlanTitulo {
            get {
                return ResourceManager.GetString("HayUnNuevoPlanTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment history.
        /// </summary>
        internal static string HistorialPagos {
            get {
                return ResourceManager.GetString("HistorialPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Man.
        /// </summary>
        internal static string Hombre {
            get {
                return ResourceManager.GetString("Hombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final Time.
        /// </summary>
        internal static string HoraFinal {
            get {
                return ResourceManager.GetString("HoraFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Time.
        /// </summary>
        internal static string HoraInicial {
            get {
                return ResourceManager.GetString("HoraInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Information.
        /// </summary>
        internal static string InformacionCuenta {
            get {
                return ResourceManager.GetString("InformacionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Information.
        /// </summary>
        internal static string InformacionPago {
            get {
                return ResourceManager.GetString("InformacionPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Information.
        /// </summary>
        internal static string InformacionPerfil {
            get {
                return ResourceManager.GetString("InformacionPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Information.
        /// </summary>
        internal static string InformacionPersonal {
            get {
                return ResourceManager.GetString("InformacionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region Information.
        /// </summary>
        internal static string InformacionRegion {
            get {
                return ResourceManager.GetString("InformacionRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        internal static string IniciaSesion {
            get {
                return ResourceManager.GetString("IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @_NombrePersona_@  is going to attend @_TituloEvento_@!..
        /// </summary>
        internal static string InscripcionEventoDescripcion {
            get {
                return ResourceManager.GetString("InscripcionEventoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Someone is going to attend one of your events!..
        /// </summary>
        internal static string InscripcionEventoTitulo {
            get {
                return ResourceManager.GetString("InscripcionEventoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructions for payment:.
        /// </summary>
        internal static string InstruccionesParaElPago {
            get {
                return ResourceManager.GetString("InstruccionesParaElPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messenger.
        /// </summary>
        internal static string Mensajeria {
            get {
                return ResourceManager.GetString("Mensajeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly.
        /// </summary>
        internal static string Mensual {
            get {
                return ResourceManager.GetString("Mensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Skills.
        /// </summary>
        internal static string MisHabilidades {
            get {
                return ResourceManager.GetString("MisHabilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show less.
        /// </summary>
        internal static string MostrarMenos {
            get {
                return ResourceManager.GetString("MostrarMenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show all.
        /// </summary>
        internal static string MostrarTodo {
            get {
                return ResourceManager.GetString("MostrarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Woman.
        /// </summary>
        internal static string Mujer {
            get {
                return ResourceManager.GetString("Mujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Will you not attend?.
        /// </summary>
        internal static string NoAsistiras {
            get {
                return ResourceManager.GetString("NoAsistiras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Camera.
        /// </summary>
        internal static string NoCamara {
            get {
                return ResourceManager.GetString("NoCamara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Gallery.
        /// </summary>
        internal static string NoGaleria {
            get {
                return ResourceManager.GetString("NoGaleria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name Contact.
        /// </summary>
        internal static string NombreContacto {
            get {
                return ResourceManager.GetString("NombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company name.
        /// </summary>
        internal static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to pick photos. Go to settings?.
        /// </summary>
        internal static string NoSePudoPickearFoto {
            get {
                return ResourceManager.GetString("NoSePudoPickearFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to pick video. Go to settings?.
        /// </summary>
        internal static string NoSePudoPickearVideo {
            get {
                return ResourceManager.GetString("NoSePudoPickearVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to take photos. Go to settings?.
        /// </summary>
        internal static string NoSePudoTomarFoto {
            get {
                return ResourceManager.GetString("NoSePudoTomarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to take videos. Go to settings?.
        /// </summary>
        internal static string NosePudoTomarVideo {
            get {
                return ResourceManager.GetString("NosePudoTomarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not validate the footprint or have it not associated with the account !..
        /// </summary>
        internal static string NoSePudoValidarHuella {
            get {
                return ResourceManager.GetString("NoSePudoValidarHuella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a News.
        /// </summary>
        internal static string Noticias {
            get {
                return ResourceManager.GetString("Noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        internal static string Notificacion {
            get {
                return ResourceManager.GetString("Notificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        internal static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Does not expire.
        /// </summary>
        internal static string NoVence {
            get {
                return ResourceManager.GetString("NoVence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Chat.
        /// </summary>
        internal static string NuevoChat {
            get {
                return ResourceManager.GetString("NuevoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of sports.
        /// </summary>
        internal static string NumeroDeportes {
            get {
                return ResourceManager.GetString("NumeroDeportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID number.
        /// </summary>
        internal static string NumeroIdentificacion {
            get {
                return ResourceManager.GetString("NumeroIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *  Required.
        /// </summary>
        internal static string Obligatorio {
            get {
                return ResourceManager.GetString("Obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feedback from the Administrator.
        /// </summary>
        internal static string ObservacionesAdmin {
            get {
                return ResourceManager.GetString("ObservacionesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Notes.
        /// </summary>
        internal static string ObservacionesPago {
            get {
                return ResourceManager.GetString("ObservacionesPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string OlvidoContraseña {
            get {
                return ResourceManager.GetString("OlvidoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        internal static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to process the purchase of the plan!..
        /// </summary>
        internal static string PagoNoSePudoRegistrar {
            get {
                return ResourceManager.GetString("PagoNoSePudoRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write us the payment reference in order to continue the process!.
        /// </summary>
        internal static string PagoReferenciaPagoNecesaria {
            get {
                return ResourceManager.GetString("PagoReferenciaPagoNecesaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for purchasing our services, we will notify you when the payment has been confirmed!.
        /// </summary>
        internal static string PagoSeRegistroEsperandoAprobacion {
            get {
                return ResourceManager.GetString("PagoSeRegistroEsperandoAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for purchasing our services, we will be waiting for payment confirmation.
        /// </summary>
        internal static string PagoSeRegistroEsperandoPago {
            get {
                return ResourceManager.GetString("PagoSeRegistroEsperandoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a payment pending, check the history of your purchases to continue with the process!.
        /// </summary>
        internal static string PagoYaHayEnTramite {
            get {
                return ResourceManager.GetString("PagoYaHayEnTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country:.
        /// </summary>
        internal static string PaisPago {
            get {
                return ResourceManager.GetString("PaisPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending For Approve.
        /// </summary>
        internal static string PendientePorAprobar {
            get {
                return ResourceManager.GetString("PendientePorAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodicity:.
        /// </summary>
        internal static string Periodicidad {
            get {
                return ResourceManager.GetString("Periodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission Denied.
        /// </summary>
        internal static string PermisoDenegado {
            get {
                return ResourceManager.GetString("PermisoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight (Kg).
        /// </summary>
        internal static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum allowed size of the video is: 100MB.
        /// </summary>
        internal static string PesoMaximoVideoPermitido {
            get {
                return ResourceManager.GetString("PesoMaximoVideoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat your password.
        /// </summary>
        internal static string PlaceHolderContraseñaVerificacion {
            get {
                return ResourceManager.GetString("PlaceHolderContraseñaVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Plan.
        /// </summary>
        internal static string PlanDeLaCuenta {
            get {
                return ResourceManager.GetString("PlanDeLaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plans.
        /// </summary>
        internal static string Planes {
            get {
                return ResourceManager.GetString("Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your plan &quot;@_NombrePlan_@&quot; is about to expire, expire on @_FechaVencimientoPlan_@!.
        /// </summary>
        internal static string PlanEstaPorVencerseDescripcion {
            get {
                return ResourceManager.GetString("PlanEstaPorVencerseDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your plan is about to expire!..
        /// </summary>
        internal static string PlanEstaPorVencerseTitulo {
            get {
                return ResourceManager.GetString("PlanEstaPorVencerseTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The purchase of the &quot;@_NombrePlan_@&quot; plan was approved!..
        /// </summary>
        internal static string PlanFueAprobadoDescripcion {
            get {
                return ResourceManager.GetString("PlanFueAprobadoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The purchase was approved!..
        /// </summary>
        internal static string PlanFueAprobadoTitulo {
            get {
                return ResourceManager.GetString("PlanFueAprobadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase of plan &quot;@_NombrePlan_@&quot; was rejected!..
        /// </summary>
        internal static string PlanFueRechazadoDescripcion {
            get {
                return ResourceManager.GetString("PlanFueRechazadoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The purchase was rejected!..
        /// </summary>
        internal static string PlanFueRechazadoTitulo {
            get {
                return ResourceManager.GetString("PlanFueRechazadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have reached the maximum amount of sports allowed for your plan, look at our subscription plans in order to increase this limit..
        /// </summary>
        internal static string PlanMaximoCategoria {
            get {
                return ResourceManager.GetString("PlanMaximoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This option is not available in your plan, check our subscription plans to access our options..
        /// </summary>
        internal static string PlanNoSoportaOperacion {
            get {
                return ResourceManager.GetString("PlanNoSoportaOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your plan &quot;@_NombrePlan_@&quot; has expired on @_FechaVencimientoPlan_@!.
        /// </summary>
        internal static string PlanSeHaVencidoDescripcion {
            get {
                return ResourceManager.GetString("PlanSeHaVencidoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your plan has expired!..
        /// </summary>
        internal static string PlanSeHaVencidoTitulo {
            get {
                return ResourceManager.GetString("PlanSeHaVencidoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portuguese.
        /// </summary>
        internal static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for joining SportsGo. We have sent a confirmation message to your email..
        /// </summary>
        internal static string ProcedeValidarCorreo {
            get {
                return ResourceManager.GetString("ProcedeValidarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post.
        /// </summary>
        internal static string Publicacion {
            get {
                return ResourceManager.GetString("Publicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publications.
        /// </summary>
        internal static string Publicaciones {
            get {
                return ResourceManager.GetString("Publicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertising.
        /// </summary>
        internal static string Publicidad {
            get {
                return ResourceManager.GetString("Publicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to associate this device with your account?.
        /// </summary>
        internal static string QuieresAsociarDispositivo {
            get {
                return ResourceManager.GetString("QuieresAsociarDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejected.
        /// </summary>
        internal static string Rechazado {
            get {
                return ResourceManager.GetString("Rechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to remember me?.
        /// </summary>
        internal static string Recuerdame {
            get {
                return ResourceManager.GetString("Recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovery.
        /// </summary>
        internal static string Recuperacion {
            get {
                return ResourceManager.GetString("Recuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful recovery, soon will arrive an email with your new data !..
        /// </summary>
        internal static string RecuperacionClaveExitosa {
            get {
                return ResourceManager.GetString("RecuperacionClaveExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Reference.
        /// </summary>
        internal static string ReferenciaPago {
            get {
                return ResourceManager.GetString("ReferenciaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        internal static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report Payment.
        /// </summary>
        internal static string ReportarPago {
            get {
                return ResourceManager.GetString("ReportarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Representative.
        /// </summary>
        internal static string Representantes {
            get {
                return ResourceManager.GetString("Representantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsible of the Sportsman.
        /// </summary>
        internal static string ResponsableCandidato {
            get {
                return ResourceManager.GetString("ResponsableCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biannual.
        /// </summary>
        internal static string Semestral {
            get {
                return ResourceManager.GetString("Semestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Name.
        /// </summary>
        internal static string SinNombre {
            get {
                return ResourceManager.GetString("SinNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tactics.
        /// </summary>
        internal static string Tacticas {
            get {
                return ResourceManager.GetString("Tacticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Techniques.
        /// </summary>
        internal static string Tecnicas {
            get {
                return ResourceManager.GetString("Tecnicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Landline phone.
        /// </summary>
        internal static string TelefonoFijo {
            get {
                return ResourceManager.GetString("TelefonoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mobile phone.
        /// </summary>
        internal static string TelefonoMovil {
            get {
                return ResourceManager.GetString("TelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application Themes.
        /// </summary>
        internal static string TermasDeLaAplicacion {
            get {
                return ResourceManager.GetString("TermasDeLaAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms and conditions of use.
        /// </summary>
        internal static string TerminosYCondiciones {
            get {
                return ResourceManager.GetString("TerminosYCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum time of the video.
        /// </summary>
        internal static string TiempoMaximoVideo {
            get {
                return ResourceManager.GetString("TiempoMaximoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum allowed time for the video is:.
        /// </summary>
        internal static string TiempoMaximoVideoPermitido {
            get {
                return ResourceManager.GetString("TiempoMaximoVideoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        internal static string TituloAlerta {
            get {
                return ResourceManager.GetString("TituloAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take photo.
        /// </summary>
        internal static string TomarFoto {
            get {
                return ResourceManager.GetString("TomarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take video.
        /// </summary>
        internal static string TomarVideo {
            get {
                return ResourceManager.GetString("TomarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location on the playing field.
        /// </summary>
        internal static string UbicacionEnElCampo {
            get {
                return ResourceManager.GetString("UbicacionEnElCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Email.
        /// </summary>
        internal static string UsarCorreo {
            get {
                return ResourceManager.GetString("UsarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Fingerprint.
        /// </summary>
        internal static string UsarHuella {
            get {
                return ResourceManager.GetString("UsarHuella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User with invalid format, no special characters are allowed!..
        /// </summary>
        internal static string UsuarioFormatoInvalido {
            get {
                return ResourceManager.GetString("UsuarioFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user does not exist!..
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user already exists!..
        /// </summary>
        internal static string UsuarioRepetido {
            get {
                return ResourceManager.GetString("UsuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration date: .
        /// </summary>
        internal static string VencePlan {
            get {
                return ResourceManager.GetString("VencePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Assistants.
        /// </summary>
        internal static string VerAsistentes {
            get {
                return ResourceManager.GetString("VerAsistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Sport.
        /// </summary>
        internal static string VerDeporte {
            get {
                return ResourceManager.GetString("VerDeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  + See Information .
        /// </summary>
        internal static string VerInformacionPersonal {
            get {
                return ResourceManager.GetString("VerInformacionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Profile.
        /// </summary>
        internal static string VerPerfil {
            get {
                return ResourceManager.GetString("VerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Plans.
        /// </summary>
        internal static string VerPlanes {
            get {
                return ResourceManager.GetString("VerPlanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version of the app.
        /// </summary>
        internal static string VersionApp {
            get {
                return ResourceManager.GetString("VersionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile videos.
        /// </summary>
        internal static string VideosPerfil {
            get {
                return ResourceManager.GetString("VideosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an account?.
        /// </summary>
        internal static string YaTienesUnaCuenta {
            get {
                return ResourceManager.GetString("YaTienesUnaCuenta", resourceCulture);
            }
        }
    }
}
