//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnunciosPaisesDTO
    {
        public int Consecutivo { get; set; }
        public int CodigoAnuncio { get; set; }
        public int CodigoPais { get; set; }
    
        public virtual AnunciosDTO Anuncios { get; set; }
        public virtual PaisesDTO Paises { get; set; }
    }
}
