//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnunciosDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnunciosDTO()
        {
            this.CategoriasAnuncios = new HashSet<CategoriasAnunciosDTO>();
            this.AnunciosContenidos = new HashSet<AnunciosContenidosDTO>();
            this.AnunciosPaises = new HashSet<AnunciosPaisesDTO>();
        }

        public int Consecutivo { get; set; }
        public int CodigoAnunciante { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<int> NumeroApariciones { get; set; }
        public Nullable<int> CodigoArchivo { get; set; }
        public string UrlPublicidad { get; set; }
        public Nullable<int> NumeroVecesClickeados { get; set; }
        public Nullable<int> NumeroVecesVistos { get; set; }
        public int CodigoTipoAnuncio { get; set; }
        public Nullable<System.DateTime> UltimaVezVisto { get; set; }
        public System.DateTime FechaInicio { get; set; }

        public virtual AnunciantesDTO Anunciantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasAnunciosDTO> CategoriasAnuncios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciosContenidosDTO> AnunciosContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciosPaisesDTO> AnunciosPaises { get; set; }
        public virtual ArchivosDTO Archivos { get; set; }
        public virtual TipoPublicacionDTO TipoPublicacion { get; set; }
    }
}
