//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatosDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidatosDTO()
        {
            this.CategoriasCandidatos = new HashSet<CategoriasCandidatosDTO>();
            this.CandidatosVideos = new HashSet<CandidatosVideosDTO>();
        }

        public int Consecutivo { get; set; }
        public int CodigoPersona { get; set; }
        public Nullable<int> CodigoResponsable { get; set; }
        public int CodigoGenero { get; set; }
        public int Estatura { get; set; }
        public int Peso { get; set; }
        public string Biografia { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Alias { get; set; }

        public virtual GenerosDTO Generos { get; set; }
        public virtual PersonasDTO Personas { get; set; }
        public virtual CandidatosResponsablesDTO CandidatosResponsables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasCandidatosDTO> CategoriasCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatosVideosDTO> CandidatosVideos { get; set; }
    }
}
