//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriasDTO()
        {
            this.CategoriasAnuncios = new HashSet<CategoriasAnunciosDTO>();
            this.CategoriasCandidatos = new HashSet<CategoriasCandidatosDTO>();
            this.CategoriasEventos = new HashSet<CategoriasEventosDTO>();
            this.CategoriasGrupos = new HashSet<CategoriasGruposDTO>();
            this.CategoriasRepresentantes = new HashSet<CategoriasRepresentantesDTO>();
            this.Habilidades = new HashSet<HabilidadesDTO>();
            this.CategoriasContenidos = new HashSet<CategoriasContenidosDTO>();
            this.CategoriasNoticias = new HashSet<CategoriasNoticiasDTO>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoArchivo { get; set; }
    
        public virtual ArchivosDTO Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasAnunciosDTO> CategoriasAnuncios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasCandidatosDTO> CategoriasCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasEventosDTO> CategoriasEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasGruposDTO> CategoriasGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasRepresentantesDTO> CategoriasRepresentantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesDTO> Habilidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasContenidosDTO> CategoriasContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasNoticiasDTO> CategoriasNoticias { get; set; }
    }
}
