//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasCandidatosDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriasCandidatosDTO()
        {
            this.HabilidadesCandidatos = new HashSet<HabilidadesCandidatosDTO>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoCandidato { get; set; }
        public int CodigoCategoria { get; set; }
        public Nullable<int> PosicionCampo { get; set; }

        public virtual CandidatosDTO Candidatos { get; set; }
        public virtual CategoriasDTO Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesCandidatosDTO> HabilidadesCandidatos { get; set; }
    }
}
