//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasNoticiasDTO
    {
        public int Consecutivo { get; set; }
        public int CodigoNoticia { get; set; }
        public int CodigoCategoria { get; set; }
    
        public virtual CategoriasDTO Categorias { get; set; }
        public virtual NoticiasDTO Noticias { get; set; }
    }
}
