//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposEventosDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GruposEventosDTO()
        {
            this.CategoriasEventos = new HashSet<CategoriasEventosDTO>();
            this.GruposEventosAsistentes = new HashSet<GruposEventosAsistentesDTO>();
            this.Notificaciones = new HashSet<NotificacionesDTO>();
        }

        public int Consecutivo { get; set; }
        public int CodigoGrupo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Creacion { get; set; }
        public int CodigoIdioma { get; set; }
        public int CodigoPais { get; set; }
        public Nullable<int> CodigoArchivo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTerminacion { get; set; }
        public string Ubicacion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasEventosDTO> CategoriasEventos { get; set; }
        public virtual GruposDTO Grupos { get; set; }
        public virtual IdiomasDTO Idiomas { get; set; }
        public virtual PaisesDTO Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposEventosAsistentesDTO> GruposEventosAsistentes { get; set; }
        public virtual ArchivosDTO Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesDTO> Notificaciones { get; set; }
    }
}
