//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposEventosAsistentesDTO
    {
        public int Consecutivo { get; set; }
        public int CodigoEvento { get; set; }
        public int CodigoPersona { get; set; }
    
        public virtual GruposEventosDTO GruposEventos { get; set; }
        public virtual PersonasDTO Personas { get; set; }
    }
}
