//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabilidadesDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HabilidadesDTO()
        {
            this.HabilidadesCandidatos = new HashSet<HabilidadesCandidatosDTO>();
            this.HabilidadesContenidos = new HashSet<HabilidadesContenidosDTO>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoCategoria { get; set; }
        public int CodigoTipoHabilidad { get; set; }
    
        public virtual CategoriasDTO Categorias { get; set; }
        public virtual HabilidadesTiposDTO HabilidadesTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesCandidatosDTO> HabilidadesCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesContenidosDTO> HabilidadesContenidos { get; set; }
    }
}
