//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class ImagenesPerfilAdministradoresDTO
    {
        public int Consecutivo { get; set; }
        public int CodigoArchivo { get; set; }
        public int CodigoUsuario { get; set; }

        public virtual ArchivosDTO Archivos { get; set; }
        public virtual UsuariosDTO Usuarios { get; set; }
    }
}
