//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class NotificacionesDTO
    {
        public int Consecutivo { get; set; }
        public int CodigoTipoNotificacion { get; set; }
        public Nullable<int> CodigoPlanNuevo { get; set; }
        public Nullable<int> CodigoPersonaDestinoAccion { get; set; }
        public Nullable<int> CodigoPersonaOrigenAccion { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<int> CodigoEvento { get; set; }

        public virtual PlanesDTO Planes { get; set; }
        public virtual TipoNotificacionDTO TipoNotificacion { get; set; }
        public virtual PersonasDTO PersonasDestinoAccion { get; set; }
        public virtual PersonasDTO PersonasOrigenAccion { get; set; }
        public virtual GruposEventosDTO GruposEventos { get; set; }
    }
}
