//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaisesDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaisesDTO()
        {
            this.AnunciosPaises = new HashSet<AnunciosPaisesDTO>();
            this.GruposEventos = new HashSet<GruposEventosDTO>();
            this.PaisesContenidos = new HashSet<PaisesContenidosDTO>();
            this.Personas = new HashSet<PersonasDTO>();
            this.NoticiasPaises = new HashSet<NoticiasPaisesDTO>();
            this.FacturaFormato = new HashSet<FacturaFormatoDTO>();
            this.HistorialPagosPersonas = new HashSet<HistorialPagosPersonasDTO>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoIdioma { get; set; }
        public int CodigoMoneda { get; set; }
        public int CodigoArchivo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciosPaisesDTO> AnunciosPaises { get; set; }
        public virtual ArchivosDTO Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposEventosDTO> GruposEventos { get; set; }
        public virtual IdiomasDTO Idiomas { get; set; }
        public virtual MonedasDTO Monedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaisesContenidosDTO> PaisesContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonasDTO> Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticiasPaisesDTO> NoticiasPaises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaFormatoDTO> FacturaFormato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPagosPersonasDTO> HistorialPagosPersonas { get; set; }
    }
}