//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonasDTO()
        {
            this.Anunciantes = new HashSet<AnunciantesDTO>();
            this.Candidatos = new HashSet<CandidatosDTO>();
            this.ChatsNoOwner = new HashSet<ChatsDTO>();
            this.ChatsOwner = new HashSet<ChatsDTO>();
            this.Grupos = new HashSet<GruposDTO>();
            this.GruposEventosAsistentes = new HashSet<GruposEventosAsistentesDTO>();
            this.ListasContactosContacto = new HashSet<ContactosDTO>();
            this.ListasContactosOwner = new HashSet<ContactosDTO>();
            this.Representantes = new HashSet<RepresentantesDTO>();
            this.NotificacionesDestinoAccion = new HashSet<NotificacionesDTO>();
            this.NotificacionesOrigenAccion = new HashSet<NotificacionesDTO>();
            this.HistorialPagosPersonas = new HashSet<HistorialPagosPersonasDTO>();
        }

        public int Consecutivo { get; set; }
        public string Nombres { get; set; }
        public int CodigoPais { get; set; }
        public int CodigoIdioma { get; set; }
        public int CodigoUsuario { get; set; }
        public Nullable<int> CodigoArchivoImagenPerfil { get; set; }
        public Nullable<int> CodigoArchivoImagenBanner { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public string Skype { get; set; }
        public string Telefono { get; set; }
        public string CiudadResidencia { get; set; }
        public string Apellidos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciantesDTO> Anunciantes { get; set; }
        public virtual ArchivosDTO ArchivosBanner { get; set; }
        public virtual ArchivosDTO ArchivosPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatosDTO> Candidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsDTO> ChatsNoOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsDTO> ChatsOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposDTO> Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposEventosAsistentesDTO> GruposEventosAsistentes { get; set; }
        public virtual IdiomasDTO Idiomas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactosDTO> ListasContactosContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactosDTO> ListasContactosOwner { get; set; }
        public virtual PaisesDTO Paises { get; set; }
        public virtual UsuariosDTO Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentantesDTO> Representantes { get; set; }
        public virtual TiposPerfilesDTO TiposPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesDTO> NotificacionesDestinoAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesDTO> NotificacionesOrigenAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPagosPersonasDTO> HistorialPagosPersonas { get; set; }
    }
}
