//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanesDTO()
        {
            this.PlanesContenidos = new HashSet<PlanesContenidosDTO>();
            this.PlanesUsuarios = new HashSet<PlanesUsuariosDTO>();
            this.Notificaciones = new HashSet<NotificacionesDTO>();
            this.HistorialPagosPersonas = new HashSet<HistorialPagosPersonasDTO>();
        }

        public int Consecutivo { get; set; }
        public System.DateTime Creacion { get; set; }
        public decimal Precio { get; set; }
        public int CodigoPeriodicidad { get; set; }
        public int PlanDefault { get; set; }
        public int VideosPerfil { get; set; }
        public int ServiciosChat { get; set; }
        public int ConsultaCandidatos { get; set; }
        public int DetalleCandidatos { get; set; }
        public int ConsultaGrupos { get; set; }
        public int DetalleGrupos { get; set; }
        public int ConsultaEventos { get; set; }
        public int CreacionAnuncios { get; set; }
        public int EstadisticasAnuncios { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public int NumeroCategoriasPermisibles { get; set; }
        public int CodigoArchivo { get; set; }
        public int NumeroAparicionesAnuncio { get; set; }
        public int NumeroDiasVigenciaAnuncio { get; set; }
        public int TiempoPermitidoVideo { get; set; }

        public virtual ArchivosDTO Archivos { get; set; }
        public virtual PeriodicidadesDTO Periodicidades { get; set; }
        public virtual TiposPerfilesDTO TiposPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanesContenidosDTO> PlanesContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanesUsuariosDTO> PlanesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesDTO> Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPagosPersonasDTO> HistorialPagosPersonas { get; set; }
    }
}
