//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuariosDTO()
        {
            this.Personas = new HashSet<PersonasDTO>();
            this.ImagenesPerfilAdministradores = new HashSet<ImagenesPerfilAdministradoresDTO>();
            this.Noticias = new HashSet<NoticiasDTO>();
        }
    
        public int Consecutivo { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public string Email { get; set; }
        public int CodigoPlanUsuario { get; set; }
        public string DeviceId { get; set; }
        public int CuentaActiva { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonasDTO> Personas { get; set; }
        public virtual TiposPerfilesDTO TiposPerfiles { get; set; }
        public virtual PlanesUsuariosDTO PlanesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesPerfilAdministradoresDTO> ImagenesPerfilAdministradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticiasDTO> Noticias { get; set; }
    }
}
