//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using Xpinn.SportsGo.DomainEntities;

namespace Xpinn.SportsGo.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsGoEntities : DbContext
    {
        public SportsGoEntities()
            : base("name=SportsGoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anunciantes> Anunciantes { get; set; }
        public virtual DbSet<Anuncios> Anuncios { get; set; }
        public virtual DbSet<AnunciosContenidos> AnunciosContenidos { get; set; }
        public virtual DbSet<AnunciosPaises> AnunciosPaises { get; set; }
        public virtual DbSet<Archivos> Archivos { get; set; }
        public virtual DbSet<ArchivosTipos> ArchivosTipos { get; set; }
        public virtual DbSet<Candidatos> Candidatos { get; set; }
        public virtual DbSet<CandidatosResponsables> CandidatosResponsables { get; set; }
        public virtual DbSet<CandidatosVideos> CandidatosVideos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CategoriasAnuncios> CategoriasAnuncios { get; set; }
        public virtual DbSet<CategoriasCandidatos> CategoriasCandidatos { get; set; }
        public virtual DbSet<CategoriasContenidos> CategoriasContenidos { get; set; }
        public virtual DbSet<CategoriasEventos> CategoriasEventos { get; set; }
        public virtual DbSet<CategoriasGrupos> CategoriasGrupos { get; set; }
        public virtual DbSet<CategoriasRepresentantes> CategoriasRepresentantes { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<ChatsEstado> ChatsEstado { get; set; }
        public virtual DbSet<ChatsMensajes> ChatsMensajes { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<GruposEventos> GruposEventos { get; set; }
        public virtual DbSet<GruposEventosAsistentes> GruposEventosAsistentes { get; set; }
        public virtual DbSet<Habilidades> Habilidades { get; set; }
        public virtual DbSet<HabilidadesCandidatos> HabilidadesCandidatos { get; set; }
        public virtual DbSet<HabilidadesContenidos> HabilidadesContenidos { get; set; }
        public virtual DbSet<HabilidadesTipos> HabilidadesTipos { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Monedas> Monedas { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<PaisesContenidos> PaisesContenidos { get; set; }
        public virtual DbSet<Periodicidades> Periodicidades { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<PlanesContenidos> PlanesContenidos { get; set; }
        public virtual DbSet<PlanesUsuarios> PlanesUsuarios { get; set; }
        public virtual DbSet<Representantes> Representantes { get; set; }
        public virtual DbSet<TiposPerfiles> TiposPerfiles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<CategoriasNoticias> CategoriasNoticias { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<NoticiasContenidos> NoticiasContenidos { get; set; }
        public virtual DbSet<NoticiasPaises> NoticiasPaises { get; set; }
        public virtual DbSet<ImagenesPerfilAdministradores> ImagenesPerfilAdministradores { get; set; }
        public virtual DbSet<TerminosCondiciones> TerminosCondiciones { get; set; }
        public virtual DbSet<FormatoEmail> FormatoEmail { get; set; }
        public virtual DbSet<TipoPublicacion> TipoPublicacion { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<TipoNotificacion> TipoNotificacion { get; set; }
        public virtual DbSet<EstadoPago> EstadoPago { get; set; }
        public virtual DbSet<FacturaFormato> FacturaFormato { get; set; }
        public virtual DbSet<TiposFormatosEmail> TiposFormatosEmail { get; set; }
        public virtual DbSet<RssFeeds> RssFeeds { get; set; }
        public virtual DbSet<HistorialPagosPersonas> HistorialPagosPersonas { get; set; }
    }
}
