//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncios()
        {
            this.CategoriasAnuncios = new HashSet<CategoriasAnuncios>();
            this.AnunciosContenidos = new HashSet<AnunciosContenidos>();
            this.AnunciosPaises = new HashSet<AnunciosPaises>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoAnunciante { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<int> NumeroApariciones { get; set; }
        public Nullable<int> CodigoArchivo { get; set; }
        public string UrlPublicidad { get; set; }
        public Nullable<int> NumeroVecesClickeados { get; set; }
        public Nullable<int> NumeroVecesVistos { get; set; }
        public int CodigoTipoAnuncio { get; set; }
        public Nullable<System.DateTime> UltimaVezVisto { get; set; }
        public System.DateTime FechaInicio { get; set; }
    
        public virtual Anunciantes Anunciantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasAnuncios> CategoriasAnuncios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciosContenidos> AnunciosContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnunciosPaises> AnunciosPaises { get; set; }
        public virtual Archivos Archivos { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
    }
}
