//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatos()
        {
            this.CategoriasCandidatos = new HashSet<CategoriasCandidatos>();
            this.CandidatosVideos = new HashSet<CandidatosVideos>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoPersona { get; set; }
        public Nullable<int> CodigoResponsable { get; set; }
        public int CodigoGenero { get; set; }
        public int Estatura { get; set; }
        public int Peso { get; set; }
        public string Biografia { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Alias { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual CandidatosResponsables CandidatosResponsables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasCandidatos> CategoriasCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatosVideos> CandidatosVideos { get; set; }
    }
}
