//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chats()
        {
            this.ChatsMensajesEnvia = new HashSet<ChatsMensajes>();
            this.ChatsMensajesRecibe = new HashSet<ChatsMensajes>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoPersonaOwner { get; set; }
        public int CodigoPersonaNoOwner { get; set; }
        public int CodigoEstado { get; set; }
        public System.DateTime Creacion { get; set; }
    
        public virtual ChatsEstado ChatsEstado { get; set; }
        public virtual Personas PersonasNoOwner { get; set; }
        public virtual Personas PersonasOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensajes> ChatsMensajesEnvia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatsMensajes> ChatsMensajesRecibe { get; set; }
    }
}
