//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GruposEventos()
        {
            this.CategoriasEventos = new HashSet<CategoriasEventos>();
            this.GruposEventosAsistentes = new HashSet<GruposEventosAsistentes>();
            this.Notificaciones = new HashSet<Notificaciones>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoGrupo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Creacion { get; set; }
        public int CodigoIdioma { get; set; }
        public int CodigoPais { get; set; }
        public Nullable<int> CodigoArchivo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTerminacion { get; set; }
        public string Ubicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasEventos> CategoriasEventos { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual Paises Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposEventosAsistentes> GruposEventosAsistentes { get; set; }
        public virtual Archivos Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
    }
}
