//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habilidades()
        {
            this.HabilidadesCandidatos = new HashSet<HabilidadesCandidatos>();
            this.HabilidadesContenidos = new HashSet<HabilidadesContenidos>();
        }
    
        public int Consecutivo { get; set; }
        public int CodigoCategoria { get; set; }
        public int CodigoTipoHabilidad { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual HabilidadesTipos HabilidadesTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesCandidatos> HabilidadesCandidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesContenidos> HabilidadesContenidos { get; set; }
    }
}
