//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesPerfilAdministradores
    {
        public int Consecutivo { get; set; }
        public int CodigoArchivo { get; set; }
        public int CodigoUsuario { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
