//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticiasPaises
    {
        public int Consecutivo { get; set; }
        public int CodigoNoticia { get; set; }
        public int CodigoPais { get; set; }
    
        public virtual Noticias Noticias { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
