//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Noticias()
        {
            this.CategoriasNoticias = new HashSet<CategoriasNoticias>();
            this.NoticiasContenidos = new HashSet<NoticiasContenidos>();
            this.NoticiasPaises = new HashSet<NoticiasPaises>();
        }
    
        public int Consecutivo { get; set; }
        public System.DateTime Creacion { get; set; }
        public string UrlPublicidad { get; set; }
        public Nullable<int> CodigoArchivo { get; set; }
        public int CodigoUsuario { get; set; }
        public int CodigoTipoNoticia { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriasNoticias> CategoriasNoticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticiasContenidos> NoticiasContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticiasPaises> NoticiasPaises { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
