//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int Consecutivo { get; set; }
        public int CodigoTipoNotificacion { get; set; }
        public Nullable<int> CodigoPlanNuevo { get; set; }
        public Nullable<int> CodigoPersonaDestinoAccion { get; set; }
        public Nullable<int> CodigoPersonaOrigenAccion { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<int> CodigoEvento { get; set; }
    
        public virtual Planes Planes { get; set; }
        public virtual TipoNotificacion TipoNotificacion { get; set; }
        public virtual Personas PersonasDestinoAccion { get; set; }
        public virtual Personas PersonasOrigenAccion { get; set; }
        public virtual GruposEventos GruposEventos { get; set; }
    }
}
