//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Anunciantes = new HashSet<Anunciantes>();
            this.Candidatos = new HashSet<Candidatos>();
            this.ChatsNoOwner = new HashSet<Chats>();
            this.ChatsOwner = new HashSet<Chats>();
            this.Grupos = new HashSet<Grupos>();
            this.GruposEventosAsistentes = new HashSet<GruposEventosAsistentes>();
            this.Representantes = new HashSet<Representantes>();
            this.ContactosPersona = new HashSet<Contactos>();
            this.ContactosOwner = new HashSet<Contactos>();
            this.NotificacionesDestinoAccion = new HashSet<Notificaciones>();
            this.NotificacionesOrigenAccion = new HashSet<Notificaciones>();
            this.HistorialPagosPersonas = new HashSet<HistorialPagosPersonas>();
        }
    
        public int Consecutivo { get; set; }
        public string Nombres { get; set; }
        public int CodigoPais { get; set; }
        public int CodigoIdioma { get; set; }
        public int CodigoUsuario { get; set; }
        public Nullable<int> CodigoArchivoImagenPerfil { get; set; }
        public Nullable<int> CodigoArchivoImagenBanner { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public string Skype { get; set; }
        public string Telefono { get; set; }
        public string CiudadResidencia { get; set; }
        public string Apellidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anunciantes> Anunciantes { get; set; }
        public virtual Archivos ArchivosBanner { get; set; }
        public virtual Archivos ArchivosPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidatos> Candidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> ChatsNoOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chats> ChatsOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupos> Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GruposEventosAsistentes> GruposEventosAsistentes { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Representantes> Representantes { get; set; }
        public virtual TiposPerfiles TiposPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> ContactosPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> ContactosOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> NotificacionesDestinoAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> NotificacionesOrigenAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPagosPersonas> HistorialPagosPersonas { get; set; }
    }
}
