//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planes()
        {
            this.PlanesContenidos = new HashSet<PlanesContenidos>();
            this.PlanesUsuarios = new HashSet<PlanesUsuarios>();
            this.Notificaciones = new HashSet<Notificaciones>();
            this.HistorialPagosPersonas = new HashSet<HistorialPagosPersonas>();
        }
    
        public int Consecutivo { get; set; }
        public System.DateTime Creacion { get; set; }
        public decimal Precio { get; set; }
        public int CodigoPeriodicidad { get; set; }
        public int PlanDefault { get; set; }
        public int VideosPerfil { get; set; }
        public int ServiciosChat { get; set; }
        public int ConsultaCandidatos { get; set; }
        public int DetalleCandidatos { get; set; }
        public int ConsultaGrupos { get; set; }
        public int DetalleGrupos { get; set; }
        public int ConsultaEventos { get; set; }
        public int CreacionAnuncios { get; set; }
        public int EstadisticasAnuncios { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public int NumeroCategoriasPermisibles { get; set; }
        public int CodigoArchivo { get; set; }
        public int NumeroAparicionesAnuncio { get; set; }
        public int NumeroDiasVigenciaAnuncio { get; set; }
        public int TiempoPermitidoVideo { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        public virtual Periodicidades Periodicidades { get; set; }
        public virtual TiposPerfiles TiposPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanesContenidos> PlanesContenidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanesUsuarios> PlanesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPagosPersonas> HistorialPagosPersonas { get; set; }
    }
}
