//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpinn.SportsGo.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Personas = new HashSet<Personas>();
            this.ImagenesPerfilAdministradores = new HashSet<ImagenesPerfilAdministradores>();
            this.Noticias = new HashSet<Noticias>();
        }
    
        public int Consecutivo { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public System.DateTime Creacion { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public int CodigoTipoPerfil { get; set; }
        public string Email { get; set; }
        public int CodigoPlanUsuario { get; set; }
        public string DeviceId { get; set; }
        public int CuentaActiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual PlanesUsuarios PlanesUsuarios { get; set; }
        public virtual TiposPerfiles TiposPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesPerfilAdministradores> ImagenesPerfilAdministradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticias> Noticias { get; set; }
    }
}
